kind = "web"
previewPath = "/"
title = "Portafolio Personal"
version = "1.0.0"
id = "artifacts/portafolio"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18885

[services.development]
run = "pnpm --filter @workspace/portafolio run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/portafolio", "run", "build" ]
publicDir = "artifacts/portafolio/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18885"
BASE_PATH = "/"
